### PR TITLE
Update Libs.

### PR DESCRIPTION
**Pull request by gerlis18**
Update library versions to newest.

### CODE REVIEW

**Comment by xBytez** [comment]
This breaks my bot.

```
/home/xbytez/srv/slack/plugdjba/node_modules/slackbotapi/node_modules/eventemitter3/index.js:66
  if (!emitter._events[evt]) emitter._events[evt] = listener, emitter._eventsCount++;
                      ^

TypeError: Cannot read property 'message' of undefined
    at addListener (/home/xbytez/srv/slack/plugdjba/node_modules/slackbotapi/node_modules/eventemitter3/index.js:66:23)
    at slackAPI.on (/home/xbytez/srv/slack/plugdjba/node_modules/slackbotapi/node_modules/eventemitter3/index.js:228:10)
    at Object.<anonymous> (/home/xbytez/srv/slack/plugdjba/bot.js:145:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
```

Line 45 in bot.js is an event listener for message.
```
slack.on('message', function(data) {
```

**Comment by gerlis18** [comment]
Done. 👍

**Comment by xBytez** [comment]
Looks good! My bot is running again, will keep it on for a few hours and if it stays stable I'll merge!

**Comment by xBytez** [comment]
Works flawlessly. Thanks!

**Pull request merged**
