### PR TITLE
Adding typing message type so bots can send "is typing..." message

### PR DESCRIPTION
**Pull request by geetotes**

### CODE REVIEW

**Comment by IgorAntun** [comment]
Hey, it seems like this branch has some merge conflicts, could you please try to fix these so I can merge them?

**Comment by geetotes** [comment]
@IgorAntun should be cleaned up!

**Comment by IgorAntun** [comment]
Looks good, thanks!

**Comment by xBytez** [comment]
Looks awesome, thanks for contributing!

**Pull request merged**
