### PR TITLE
slackData now updates when user presence changes

### PR DESCRIPTION
**Pull request by franciskim**
also removed unnecessary function (that I created xD)

### CODE REVIEW

**Comment by Hunchmun** [comment]
Ok, in order to keep semver, we'd need to update to v2...

**Comment by franciskim** [comment]
@Hunchmun v2 already? This is pretty minor though

**Comment by Hunchmun** [comment]
Well, as minor as it is, removing a function is a backward incompatible change, if people are using it :/

**Comment by franciskim** [comment]
@Hunchmun I don't think anyone would be using it, there was no need to call the function in the first place, as you can just access it from the object instance itself. But I'm happy to re-commit without removing the function depending on what the 3rd person says.

**Comment by xBytez** [comment]
@Hunchmun That's up to you! I do like to go by SemVer.

**Comment by franciskim** [comment]
@xBytez @Hunchmun ok, agree with you guys - so I'll create a new pull request :)

**Pull request closed without merging**
